version: '3'
services:
  users_server:
    build: ./users_server
    command: node index.js
    ports:
      - "3000:3000"
    volumes:
      - ./users_server:/usr/src/app/users_server
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
  groups_server:
    build: ./groups_server
    command: node index.js
    ports:
      - "3001:3001"
    volumes:
      - ./groups_server:/usr/src/app/groups_server
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"

    ports:
      - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"

    ports:
      - "1234:1234"
